cmake_minimum_required(VERSION 3.10)

macro(build_src_files_list _dir _submit)
    # Search for c++ files
    file(GLOB_RECURSE CPP_FILES RELATIVE "${_dir}" "${_dir}/*.c*" "${_dir}/*.h*" "${_dir}/*.inl")
    foreach(file ${CPP_FILES})
        list(FIND SRC_FILES "${file}" index)
        if (index EQUAL -1)
            get_filename_component(dir "${file}" DIRECTORY)
            list(APPEND SRC_FILES "${file}")
            if(${_submit})
                list(APPEND SUBMISSION_FILES "${_dir}/${file}")
            endif()
            if (NOT dir STREQUAL "")
                string(REPLACE "/" "\\" "${dir}" dir)
                source_group("Source Files\\${dir}" FILES "${file}")
            endif()
        endif()
    endforeach()

    # Search for header files to include to all.h
    set(ALL_H "#ifndef ALL_H\n#define ALL_H\n\n")
    file(GLOB_RECURSE H_FILES RELATIVE "${_dir}" "${_dir}/*.h" "${_dir}/*.hh")
    foreach(file ${H_FILES})
        list(FIND SRC_FILES "${file}" index)
        if (NOT file STREQUAL "all.h")
            set(ALL_H "${ALL_H}#include \"${file}\"\n")
        endif()
    endforeach()
    set(ALL_H "${ALL_H}\n#endif\n")
    file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/all.h" "${ALL_H}")
endmacro()
